### ISSUE TITLE
STS is not run: Windows authentication pop-up is shown

### ISSUE THREAD

**Issue by alexandis** [primaryobjects/SingleSignOn#1]
When I'm being redirected to STS, it shows pop-up for entering Windows credentials, although only forms authentication is enabled for STS site.
Did I miss something in the settings of STS?
You have mentioned bindings ("For the bindings, use the host name "customsts.dev" and choose port 80"), but not in details. Could it be the reason?
I have added new binding for IP "All Unassigned", with host name = "customsts.dev" and port 80, but alas, nothing changed.

**Comment by primaryobjects** [comment]
This could be IIS-related. Check your settings for the site in IIS to make sure Anonymous Authentication is enabled. http://stackoverflow.com/questions/5402381/receiving-login-prompt-using-integrated-windows-authentication

**Comment by alexandis** [comment]
I have added IUSR into permission list and now everything is ok :)
