### ISSUE TITLE
Not a complain, rather a proposal: automatic SSO

### ISSUE THREAD

**Issue by alexandis** [primaryobjects/SingleSignOn#2]
Hi,
I'd suggest to add automatic log-on.
I'm not sure what is the best way to implement it - still new to it.
But in my case SSO from you example - it's rather a portal, not just a plain submit form.
So, the points are:
1) if a non-authenticated user tries to access RP site - he's automatically redirected to SSO login form
2) a user may log in from SSO, going to its site directly, in this case he's not redirected anywhere, he stays logged in there, but offered a list of app he can visit, one of them is RP from your example (link is provided)

I wonder what is the best way to implement automatic log-on (calling RedirectToIdentityProvider method)....

Another problem is - I have the following issue:
"ID4175: The issuer of the security token was not recognized by the IssuerNameRegistry.".

This is a part of web.config:

```
        <issuerNameRegistry type="System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry, System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
            <trustedIssuers>
                <add name="http://localhost/loginpoint.dev/" thumbprint="‎15e90fb4efaa1b9e42e9d77992a262f0c3c72c40" />
            </trustedIssuers>
        </issuerNameRegistry>
```

(I have not made anything in hosts and my sts name is http://localhost/loginpoint.dev, not http://customsts.dev as in example).

And thumbprint is what I copied from .cer file and deleted spaces between. What to be checked?

Thanks!

**Comment by primaryobjects** [comment]
For the problem of "ID4175: The issuer of the security token was not recognized by the IssuerNameRegistry.", this is usually caused by a miss-typed character in the thumbprint key, lowercase characters (they should all be in uppercase), or hidden control characters within the text (which can occur when copying and pasting from the certificate dialog into the web.config). To resolve this, I recommend manually typing the thumbprint into the web.config using all uppercase characters and avoid copying/pasting the thumbprint. You can verify with the following steps:
1. Select web.config in visual studio.
2. Pick Open With, Binary Editor.
3. Look for hidden control characters in thumbprint. Verify thumbprint is all upper-case characters. Verify name (next to thumbprint) matches certificate issue name "CN=something.domain.com" in web.config for sso site and client site.

For automatically logging the user in and redirecting anonymous users to the single-sign-on login page, you can do this in your page controller:

```
public ActionResult Index()
{
HttpRequest request = HttpContext.Current.Request;
redirectUrl = request.Url.PathAndQuery;

if (!HttpContext.Current.User.Identity.IsAuthenticated)
{
   // Set user to return to this login page so we can authenticate them locally and then send them to the target page.
   if (!redirectUrl.ToLower().StartsWith("/login"))
   {
      redirectUrl = "/login?url=" + redirectUrl;
   }

   FederatedAuthentication.WSFederationAuthenticationModule.RedirectToIdentityProvider(relyingPartyApplicationId, redirectUrl, true);
}
else
{
   // User is already authenticated, manually log in the user.
   var user = LoadUser(HttpContext.Current.User.Identity.Name);
   if (user != null)
   {
      if (redirectUrl.ToLower().Contains("/login?url="))
      {
          // Extract redirect url.
          redirectUrl = redirectUrl.Substring(11);
          if (string.IsNullOrEmpty(redirectUrl))
          {
              redirectUrl = "/";
          }
      }
      else if (redirectUrl.ToLower().Contains("/login"))
      {
          // Prevent infinite redirects.
          redirectUrl = request.Url.Scheme + "://" + request.Url.Host;
          if (!request.Url.IsDefaultPort)
          {
              redirectUrl += ":" + request.Url.Port;
          }

          // When redirecting to the homepage, skip an extra redirect (from https to http) by switching it here.
          Uri uri = new Uri(redirectUrl);
          if (uri.PathAndQuery == "/")
          {
              redirectUrl = redirectUrl.Replace("https://", "http://");
          }
      }

      // User is now logged in, redirect user to logged-in page.
      return Redirect(redirectUrl);
   }
   else
   {
      // Login denied. User may not have access to this app.
      throw new HttpException(403, "Error during login.");
   }
}

return View();
}
```

**Comment by alexandis** [comment]
Thank you very much, your advice about binary editor was very helpful, I could not expect some unreadable characters would come through!
But I still suffer a lot of problems because of those cross-site redirections. Maybe one of the reason is my MVC route - I have a culture parameters, standing in front of controller name, so it should be taken into account (I've tried to create a separate rule for Login page to take care of forms loginUrl constant, which neglects a culture).
However, I am getting infinite redirects when trying to log-in and log-out from my RP site and so on.
Here is the project I'm trying to apply your solution to, of course, it's changed to suite some specific needs. Autoredirection still not implemented, I'm so afraid of these url parsings and string concatenations...
Please, if you get a chance to have a quick look at what's wrong here - will be greatly appreciated!
https://www.dropbox.com/s/23blq5davomqfp9/Prototype.zip

I also see my user as authenticated on RP after making logging out at STS site now...

**Comment by primaryobjects** [comment]
Re: I also see my user as authenticated on RP after making logging out at STS site now.

In addition to logging out of single-sign-on, you also need to logout of the local sites. This lets you delete 2+ cookies (one from the single sign-on domain and one from each relying party domain). You can do this upon logout of SSO by redirecting to an intermediate page that has IMG tag links pointing to logout urls on each relying party. After the logout page finishes loading (and thus, signs you out of all of the relying party sites) you're finally redirected back to the wreply url, which takes you back to the relying party web site.

SSO Logout.cshtml (also see https://github.com/primaryobjects/SingleSignOn/blob/master/SingleSignOn/Views/Logout/Index.cshtml)

``` html
    @if (!string.IsNullOrEmpty(Request.QueryString["wreply"]))
    {
        <script type="text/javascript">
            // Redirect back to relying party web site only after each relying party logout url has been called.
            $(window).load(function () {
                document.location = '@Request.QueryString["wreply"]';
            });
        </script>
    }

<!-- Relying party sign-out urls -->
<img src="http://localhost:22454/logout" style="width: 1px; height: 1px;" />
<img src="http://some-other-domain.com/account/logout" style="width: 1px; height: 1px;" />
```

**Comment by alexandis** [comment]
Thanks. Finally i got everything working, with some modifications (not using deprecated methods from 3.5 according to MSDN)...
But now - just not to create a separate question - I wonder how to make this STS work with WCF service? I've made the changes to the service's web.config via Identity tools, made some small modifications. But it's not enough (for instance, there is mex endpoint indicated in web.config, which of course gives 404 error, etc... guess there will be more errors further). And I cannot find a good example - like this one, but for working with WCF...

**Comment by Ruffio** [comment]
@alexandis can this 'issue' be closed?

**Comment by alexandis** [comment]
I suppose yes, because I finally abandoned the idea... :)
